name: micuotaapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.3.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.5.0
  intl: ^0.17.0
  provider: ^6.1.2 # Para manejar el estado si lo necesitas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/avatar1.png
    - lib/assets/images/avatar2.png
    - lib/assets/images/avatar3.png
    - lib/assets/images/avatar4.png
    - lib/assets/images/avatar5.png
    - lib/assets/images/avatar6.png
    - lib/assets/images/avatar7.png
    - lib/assets/images/avatar8.png
    - lib/assets/images/avatar9.png
    - lib/assets/images/avatar10.png
    - lib/assets/images/avatar11.png
    - lib/assets/images/avatar12.png
    - lib/assets/images/avatar13.png
    - lib/assets/images/avatar14.png
    - lib/assets/images/avatar15.png
    - lib/assets/images/avatar16.png
    - lib/assets/images/avatar18.png
    - lib/assets/images/avatar19.png
    - lib/assets/images/avatar20.png
    - lib/assets/images/avatar21.png
    - lib/assets/images/avatar22.png
    - lib/assets/images/avatar23.png
    - lib/assets/images/3dicons-wallet-iso-color.png
    - lib/assets/images/calendar.png

  fonts:
    - family: Outfit
      fonts:
        - asset: lib/assets/fonts/Outfit-VariableFont_wght.ttf
